In [24]:
import numpy as np

from numpy import *

In [44]:
oweight1 = np.load("oweight1.npy")
oweight2 = np.load("oweight2.npy")
oweight3 = np.load("oweight3.npy")
oweight4 = np.load("oweight4.npy")
obias1 = np.load("obias1.npy")
obias2 = np.load("obias2.npy")
obias3 = np.load("obias3.npy")
obias4 = np.load("obias4.npy")
ofcweight1 = np.load("ofcweight1.npy")
ofcweight2 = np.load("ofcweight2.npy")
ofcbias1 = np.load("ofcbias1.npy")
ofcbias2 = np.load("ofcbias2.npy")

In [17]:
def Conv(inChannel,outChannel,size,img,kernel,bias):
    out = np.zeros((outChannel,size-2,size-2)) 
#     out = out.to(torch.int16)
    for p in range(outChannel):
        for i in range(size-2):
            for j in range(size-2):
                out[p][i][j] = bias[p]
    
    for q in range(inChannel):
        for p in range(outChannel):
            for i in range(size-2):
                for j in range(size-2):
                    for m in range (3):
                        for n in range(3):
                            out[p][i][j] = out[p][i][j] + kernel[p][q][m][n]*img[q][i+m][j+n]
#                             if( InChannel == 64 and i == 0 and j == 0 and p == 0):
#                                 print(img[q][i+m][j+n].item(),kernel[p][q][m][n].item(),out[p][i][j].item())
    return out    
    
def Pooling(Channel,size,img):
    print(size)
    out = np.zeros((Channel,int(size),int(size)))
    for i in range(Channel):
        for j in range(size):
            for k in range(size):
                out[i][j][k] = max(img[i][j*2][k*2],img[i][j*2+1][k*2],img[i][j*2][k*2+1],img[i][j*2+1][k*2+1])
    return out

def Pooling_3(Channel,size,img):
    print(size)
    out = np.zeros((Channel,int(size),int(size)))
    for i in range(Channel):
        for j in range(size):
            for k in range(size):
                out[i][j][k] = max(img[i][j*3][k*3],img[i][j*3+1][k*3],img[i][j*3+2][k*3],img[i][j*3][k*3+1],img[i][j*3+1][k*3+1],img[i][j*3+2][k*3+1],img[i][j*3][k*3+2],img[i][j*3+1][k*3+2],img[i][j*3+2][k*3+2])
    return out

In [64]:

img = np.array([[[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,1,1,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]]])



# img = img.view(1,28,28)


h1 = Conv(1,16,28,img,oweight1,obias1)
h1 = h1 * 0.0078125
# h1 = torch.round(h1)
# h1 = h1.to(torch.int16)
h1 = h1.clip(0,256)
print(h1)


h2 = Conv(16,32,26,h1,oweight2,obias2)
h2 = h2 * 0.00390625
# h2 = torch.round(h2)
# h2 = h2.to(torch.int16)
h2 = h2.clip(0,256)
#print(h2.dtype)
h2 = Pooling(32,12,h2)
# save_3D("h2.txt",h2.to(torch.int16))


h3 = Conv(32,64,12,h2,oweight3,obias3)
# save_3D("h3_NS.txt",h3.to(torch.int16))
h3 = h3 * 0.001953125
# h3 = torch.round(h3)
# h3 = h3.to(torch.int16)
h3 = h3.clip(0,256)
h3 = Pooling(64,5,h3)
# save_3D("h3.txt",h3.to(torch.int16))
# #print(h3)

h4 = Conv(64,64,5,h3,oweight4,obias4)
# save_3D("h4_NS.txt",h4.to(torch.int16))
h4 = h4 * 0.00390625
# h4 = h4.to(torch.int16)
h4 = h4.clip(0,256)
# save_3D("h4.txt",h4.to(torch.int16))
h4 = Pooling_3(64,1,h4)

# h4 = torch.round(h4)
# h4 = h4.to(torch.int16)
# print(h4.size())
h4 = h4.reshape(1,-1)

h5 = np.mat(h4)* np.mat(ofcweight1.T)
# h5 = h4 * ofcweight1.T()
h5 = h5 + ofcbias1
h5 = h5*0.00390625
h5 = h5.clip(0,256)

h6 = np.mat(h5)* np.mat(ofcweight2.T)
# h6 = h6 * ofcweight2.T()
h6 = h6 + ofcbias2
h6 = h6 *0.0078125
h6 = h6.clip(0,256)
# i = i + 1
print("h6",h6)

# print("out",out)
# print("pred",pred)
# print("label",label)

[[[0.0703125 0.0703125 0.0703125 ... 0.0703125 0.0703125 0.0703125]
  [0.0703125 0.0703125 0.0703125 ... 0.0703125 0.0703125 0.0703125]
  [0.0703125 0.0703125 0.0703125 ... 0.0703125 0.0703125 0.0703125]
  ...
  [0.0703125 0.0703125 0.0703125 ... 0.0703125 0.0703125 0.0703125]
  [0.0703125 0.0703125 0.0703125 ... 0.0703125 0.0703125 0.0703125]
  [0.0703125 0.0703125 0.0703125 ... 0.0703125 0.0703125 0.0703125]]

 [[0.1640625 0.1640625 0.1640625 ... 0.1640625 0.1640625 0.1640625]
  [0.1640625 0.1640625 0.1640625 ... 0.1640625 0.1640625 0.1640625]
  [0.1640625 0.1640625 0.1640625 ... 0.1640625 0.1640625 0.1640625]
  ...
  [0.1640625 0.1640625 0.1640625 ... 0.1640625 0.1640625 0.1640625]
  [0.1640625 0.1640625 0.1640625 ... 0.1640625 0.1640625 0.1640625]
  [0.1640625 0.1640625 0.1640625 ... 0.1640625 0.1640625 0.1640625]]

 [[0.1484375 0.1484375 0.1484375 ... 0.1484375 0.1484375 0.1484375]
  [0.1484375 0.1484375 0.1484375 ... 0.1484375 0.1484375 0.1484375]
  [0.1484375 0.1484375 0.1484375

In [60]:
h5 = np.mat(h4)* np.mat(ofcweight1.T)


In [61]:
h5.shape


(1, 32)

In [58]:
h5.shape


(64, 32)